name: Code Quality Check

on:
  push:
    branches:
      - 'develop'
    paths:
      - 'app/**.py'
      - 'requirements*.*'
      - 'Dockerfile*'
      - 'docker-compose*.yml'
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'app/**.py'
      - 'requirements*.*'
      - 'Dockerfile*'
      - 'docker-compose*.yml'
      - '.github/workflows/*.yml'

jobs:
  static_analysis:
    name: Run static analysis
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Black & Ruff with latest pip
      run: |
        python -m pip install --upgrade pip
        cat ./requirements-dev.txt | grep black== | cut -d' ' -f1 | xargs pip install
        cat ./requirements-dev.txt | grep ruff== | cut -d' ' -f1 | xargs pip install

    - name: Lint files using Ruff
      run: |
        ruff check ./app

    - name: Check formatting with Black
      run: |
        black --line-length 120 --target-version py311 --check ./app
