on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

name: Build Docker image and push to Gcloud

env:
  GCE_INSTANCE: ${{ secrets.GCE_INSTANCE }}
  GCE_INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE }}

jobs:

  build:
    name: Build Docker image
    uses: code4romania/.github/.github/workflows/build-push-image.yml@main
    with:
      images: code4romania/redirectioneaza-zipping
    secrets:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  push-to-gcloud:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: code4romania/redirectioneaza-zipping
          tags: |
            type=edge
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}


      - id: 'auth'
        uses: 'google-github-actions/auth@v1.1.1'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1.1.1'

      - name: Deploy to GCP
        shell: bash
        run: |-
          echo "Deploying revision ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }} to GCP"
          gcloud compute instances update-container ${GCE_INSTANCE} \
            --zone ${GCE_INSTANCE_ZONE} \
            --container-image "code4romania/redirectioneaza-zipping:edge"
