on:
  push:
    branches:
      - main

name: Deploy to GCompute

jobs:
  push-to-gcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Decrypt large secret
        run: ./.deploy/decrypt_secret.sh
        env:
          STORAGE_CREDENTIALS_PASSPHRASE: ${{ secrets.STORAGE_CREDENTIALS_PASSPHRASE }}

      - name: Deploy to GCloud
        run: ./.deploy/google-deploy.sh
        env:
          INSTANCE_NAME: ${{ secrets.INSTANCE_NAME }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
